### ISSUE TITLE
Learn API

### ISSUE THREAD

**Issue by batazor** [shortlink-org/shortlink#1645]
##### Links

- [ ] [Использование Accept Header для версионирования API](https://habr.com/ru/post/240817/)
- [ ] [Swagger MIME-types](https://swagger.io/docs/specification/2-0/mime-types/)

```[tasklist]
### Todo
- [ ] Use HTTP `Accept: application/vnd.api+json; version=1` for versionnning API
- [ ] Postman
- [ ] Front-end
- [ ] Back-end
```

#### Package

- [ ] Check version [hashicorp/go-version](https://github.com/hashicorp/go-version)

------------------------------------------------------------------------------------------------------------------------------------------

### Addinional format

------------------------------------------------------------------------------------------------------------------------------------------

#### SOAP

- [ ] https://github.com/tiaguinho/gosoap
- [ ] https://levelup.gitconnected.com/golang-soap-based-services-ccc4b3e3ee2e
- [ ] https://fale.io/blog/2018/12/03/calling-a-soap-service-in-go/

------------------------------------------------------------------------------------------------------------------------------------------

#### FastHTTP

- [ ] https://github.com/valyala/fasthttp
- [ ] Benchmark (k6s)

------------------------------------------------------------------------------------------------------------------------------------------

#### CloudEvent

- [ ] Init

------------------------------------------------------------------------------------------------------------------------------------------

#### MQTT

- [ ] Init
