### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by batazor** [shortlink-org/shortlink#226]
### To-Do

- https://medium.com/flutter-community
- [ ] [Пишем приложение на Flutter в связке с Redux](https://habr.com/ru/post/481624/)
- [ ] [Состояние Flutter на изолятах](https://habr.com/ru/post/532862/)

### CI

- [ ] https://medium.com/@fezu54/our-story-with-flutter-and-gitlab-ci-26bd40c26155
