### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by batazor** [shortlink-org/shortlink#234]
### To-Do

- [x] Add pagination to API
- [x] Add pagination to Store
- [ ] Update test

### Link

- pagination type:
  - offset
  - token
  - cursor

### Docs

- [x] [How To Do Pagination in Postgres with Golang in 4 Common Ways](https://medium.com/easyread/how-to-do-pagination-in-postgres-with-golang-in-4-common-ways-12365b9fb528)
- [x] https://shopify.engineering/pagination-relative-cursors

### So:

- Use cursor option for field with index
