### ISSUE TITLE
Guide to Kubernetes Egress Network Policies

### ISSUE THREAD

**Issue by batazor** [shortlink-org/shortlink#351]
### To-Do

- [x] Setting network
 - [x] Deny all (exclude DNS)
 - [x] Link end-to-end
 - [x] Ethernet for service `shortlink`

### Link

- [Enforce Ingress Best Practices Using OPA](https://www.cncf.io/blog/2020/09/29/enforce-ingress-best-practices-using-opa/)
- https://www.cncf.io/blog/2020/02/10/guide-to-kubernetes-egress-network-policies/
- https://www.cncf.io/blog/2020/08/25/enforce-pod-security-policies-in-kubernetes-using-opa/
- https://www.cncf.io/blog/2020/09/09/how-to-enforce-kubernetes-network-security-policies-using-opa/
