### ISSUE TITLE
Profile-guided optimization

### ISSUE THREAD

**Issue by batazor** [shortlink-org/shortlink#6518]
### Describe the solution you'd like

Profile-guided optimization (PGO), also known as feedback-directed optimization (FDO), is a compiler optimization technique that feeds information (a profile) from representative runs of the application back into to the compiler for the next build of the application, which uses that information to make more informed optimization decisions. For example, the compiler may decide to more aggressively inline functions which the profile indicates are called frequently.

In Go, the compiler uses CPU pprof profiles as the input profile, such as from [runtime/pprof](https://pkg.go.dev/runtime/pprof) or [net/http/pprof](https://pkg.go.dev/net/http/pprof).

As of Go 1.20, benchmarks for a representative set of Go programs show that building with PGO improves performance by around 2-4%. We expect performance gains to generally increase over time as additional optimizations take advantage of PGO in future versions of Go.

### To-Do

- [ ] Change CI/CD
  - [ ] Step 1: Get pprof for production service
  - [ ] Step 2: Rebuild with use profile
  - [ ] Step 3: deploy [tag]-pprof
