### ISSUE TITLE
new service: stats

### ISSUE THREAD

**Issue by batazor** [shortlink-org/shortlink#891]
Add new service `stats`

+ save stats by event: CRUD links

### ToDo

- [ ] Init
- [ ] Subscribe on event
  - [ ] Subscribe to MQ
  - [ ] Subscribe to RPC
- [ ] Save state to DB
  - [  ] InfluxDB 2.0
- [ ] Grafana
  - [ ] Dashboard
